from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]

DATA_DIR = PROJECT_ROOT / "data"
RAW_DIR = DATA_DIR / "raw"
INTERIM_DIR = DATA_DIR / "interim"
PROCESSED_DIR = DATA_DIR / "processed"

RAW_COMCAT_DIR = RAW_DIR / "comcat"
RAW_MOMENT_TENSOR_DIR = RAW_DIR / "moment_tensor"

INTERIM_COMCAT_DIR = INTERIM_DIR / "comcat"
INTERIM_MOMENT_TENSOR_DIR = INTERIM_DIR / "moment_tensor"
INTERIM_ENRICHED_DIR = INTERIM_DIR / "enriched"
INTERIM_TRIGGERS_DIR = INTERIM_DIR / "triggers"
INTERIM_LABELS_DIR = INTERIM_DIR / "labels"
INTERIM_FEATURES_DIR = INTERIM_DIR / "features"

PROCESSED_DATASETS_DIR = PROCESSED_DIR / "datasets"
PROCESSED_SPLITS_DIR = PROCESSED_DIR / "splits"

MODELS_DIR = PROJECT_ROOT / "models"
REPORTS_DIR = PROJECT_ROOT / "reports"
METRICS_DIR = REPORTS_DIR / "metrics"

ARCHIVE_DIR = PROJECT_ROOT / "archive"

# Backward-compatible aliases for reused v1 ingestion helpers.
COMCAT_RAW_DIR = RAW_COMCAT_DIR
COMCAT_INTERIM_DIR = INTERIM_COMCAT_DIR
COMCAT_PROCESSED_DIR = PROCESSED_DATASETS_DIR
